import { UserService } from '../services/user.service';
import { AdminDataService } from '../services/adminData.service';
import { isMongoConnected } from '../config/database';

const INITIAL_AIRCRAFT = [
  {
    name: 'Bombardier Global 7500',
    manufacturer: 'Bombardier',
    model: 'Global 7500',
    category: 'Ultra Long Range',
    tailNumber: '9H-AYLA1',
    registration: 'Malta (9H)',
    passengerCapacity: 14,
    maxRangeNm: 7700,
    cruiseSpeedKts: 516,
    hourlyRate: 14500,
    hourlyFuelBurnGal: 480,
    baggageCapacityCuFt: 195,
    cabinDimensions: { heightM: 1.88, widthM: 2.44, lengthM: 16.59 },
    amenities: ['Master Suite Bed', 'Nuage Ergonomic Seats', 'Four Living Zones', 'Full Galley Kitchen', 'Ka-Band WiFi', 'Stand-up Shower'],
    images: ['https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80'],
    status: 'available',
    description: 'The industry flagship. Featuring four true living spaces, a dedicated master suite with permanent bed, and ultra-high-speed Ka-band connectivity.',
    baseAirportIcao: 'LSGG',
  },
  {
    name: 'Gulfstream G650ER',
    manufacturer: 'Gulfstream Aerospace',
    model: 'G650ER',
    category: 'Ultra Long Range',
    tailNumber: 'N650AY',
    registration: 'United States (FAA)',
    passengerCapacity: 16,
    maxRangeNm: 7500,
    cruiseSpeedKts: 516,
    hourlyRate: 13800,
    hourlyFuelBurnGal: 470,
    baggageCapacityCuFt: 195,
    cabinDimensions: { heightM: 1.95, widthM: 2.59, lengthM: 14.27 },
    amenities: ['16 Panoramic Oval Windows', 'Ultra-Low Cabin Altitude', 'Convertible Divan Beds', 'HD Entertainment Suite', 'High-Speed Satellite Data'],
    images: ['https://images.unsplash.com/photo-1583416750470-965b2707b355?auto=format&fit=crop&w=1200&q=80'],
    status: 'available',
    description: 'World-renowned performance and speed. Iconic panoramic oval windows, whisper-quiet cabin altitude of 3,290 feet, and intercontinental range.',
    baseAirportIcao: 'KTEB',
  },
  {
    name: 'Dassault Falcon 8X',
    manufacturer: 'Dassault Aviation',
    model: 'Falcon 8X',
    category: 'Heavy Jet',
    tailNumber: 'F-HAYL',
    registration: 'France (DGAC)',
    passengerCapacity: 12,
    maxRangeNm: 6450,
    cruiseSpeedKts: 470,
    hourlyRate: 11200,
    hourlyFuelBurnGal: 380,
    baggageCapacityCuFt: 140,
    cabinDimensions: { heightM: 1.88, widthM: 2.34, lengthM: 13.0 },
    amenities: ['Trijet Safety Margin', 'Short-Runway Access', 'Acoustic Soundproofing', 'Custom Dining Table', 'Direct Airfield Approvals'],
    images: ['https://images.unsplash.com/photo-1569629743817-70d8db6c323b?auto=format&fit=crop&w=1200&q=80'],
    status: 'available',
    description: 'Trijet reliability and unrivaled short-field performance. Access challenging airports like London City or Aspen effortlessly with supreme cabin comfort.',
    baseAirportIcao: 'LFMN',
  },
  {
    name: 'Cessna Citation Latitude',
    manufacturer: 'Textron Aviation',
    model: 'Citation Latitude',
    category: 'Super Midsize',
    tailNumber: 'N440AY',
    registration: 'United States (FAA)',
    passengerCapacity: 9,
    maxRangeNm: 2700,
    cruiseSpeedKts: 446,
    hourlyRate: 6400,
    hourlyFuelBurnGal: 240,
    baggageCapacityCuFt: 127,
    cabinDimensions: { heightM: 1.83, widthM: 1.96, lengthM: 6.63 },
    amenities: ['Flat-Floor Cabin', 'Wireless Cabin Management', 'Spacious Refreshment Center', 'Clarity Audio', 'Fast Cruising Altitudes'],
    images: ['https://images.unsplash.com/photo-1508873696983-2df5703bc2e0?auto=format&fit=crop&w=1200&q=80'],
    status: 'available',
    description: 'The best-selling midsize business jet. Wide, flat-floor cabin with exceptional regional efficiency across North America and Europe.',
    baseAirportIcao: 'KTEB',
  },
  {
    name: 'Pilatus PC-24 Super Versatile',
    manufacturer: 'Pilatus Aircraft',
    model: 'PC-24',
    category: 'Super Light Jet',
    tailNumber: 'HB-VAY',
    registration: 'Switzerland (FOCA)',
    passengerCapacity: 8,
    maxRangeNm: 2000,
    cruiseSpeedKts: 440,
    hourlyRate: 4800,
    hourlyFuelBurnGal: 175,
    baggageCapacityCuFt: 90,
    cabinDimensions: { heightM: 1.55, widthM: 1.69, lengthM: 7.01 },
    amenities: ['Cargo Door Access', 'Unpaved Runway Certified', 'Bespoke Executive Leather', 'Continuous Cabin Altitude Control'],
    images: ['https://images.unsplash.com/photo-1520437358207-323b43b50729?auto=format&fit=crop&w=1200&q=80'],
    status: 'available',
    description: 'The world’s first and only Super Versatile Jet. Engineered in Stans, Switzerland with unique unpaved runway capability to reach remote runways.',
    baseAirportIcao: 'LSGG',
  },
];

const INITIAL_AIRPORTS = [
  {
    icao: 'OKKK',
    iata: 'KWI',
    name: 'Kuwait International Airport',
    city: 'Kuwait City',
    country: 'Kuwait',
    lat: 29.2268,
    lon: 47.9789,
    timezone: 'UTC+3',
    elevationFt: 206,
    runwayLengthFt: 11155,
    handlingFeeBase: 1850,
    landingFeeRate: 6.2,
    parkingFeeDaily: 350,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'KTEB',
    iata: 'TEB',
    name: 'Teterboro Executive Airport',
    city: 'New York / NJ',
    country: 'United States',
    lat: 40.8501,
    lon: -74.0608,
    timezone: 'UTC-5',
    elevationFt: 9,
    runwayLengthFt: 7000,
    handlingFeeBase: 3200,
    landingFeeRate: 8.5,
    parkingFeeDaily: 480,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'EGGW',
    iata: 'LTN',
    name: 'London Luton Airport',
    city: 'London',
    country: 'United Kingdom',
    lat: 51.8747,
    lon: -0.3683,
    timezone: 'UTC+0',
    elevationFt: 526,
    runwayLengthFt: 7087,
    handlingFeeBase: 3100,
    landingFeeRate: 8.2,
    parkingFeeDaily: 450,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'OMDB',
    iata: 'DXB',
    name: 'Dubai International Airport / Al Maktoum',
    city: 'Dubai',
    country: 'United Arab Emirates',
    lat: 25.2532,
    lon: 55.3657,
    timezone: 'UTC+4',
    elevationFt: 62,
    runwayLengthFt: 14764,
    handlingFeeBase: 2800,
    landingFeeRate: 7.9,
    parkingFeeDaily: 400,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'LSGG',
    iata: 'GVA',
    name: 'Geneva Cointrin Airport',
    city: 'Geneva',
    country: 'Switzerland',
    lat: 46.2381,
    lon: 6.1089,
    timezone: 'UTC+1',
    elevationFt: 1411,
    runwayLengthFt: 12795,
    handlingFeeBase: 3400,
    landingFeeRate: 9.1,
    parkingFeeDaily: 520,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'LFMN',
    iata: 'NCE',
    name: 'Nice Côte d’Azur Airport',
    city: 'Nice',
    country: 'France',
    lat: 43.6584,
    lon: 7.2159,
    timezone: 'UTC+1',
    elevationFt: 13,
    runwayLengthFt: 9744,
    handlingFeeBase: 3600,
    landingFeeRate: 9.4,
    parkingFeeDaily: 550,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'VHHH',
    iata: 'HKG',
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    country: 'Hong Kong SAR',
    lat: 22.308,
    lon: 113.9185,
    timezone: 'UTC+8',
    elevationFt: 28,
    runwayLengthFt: 12467,
    handlingFeeBase: 3800,
    landingFeeRate: 9.5,
    parkingFeeDaily: 600,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
  {
    icao: 'OERK',
    iata: 'RUH',
    name: 'King Khalid International Airport',
    city: 'Riyadh',
    country: 'Saudi Arabia',
    lat: 24.9576,
    lon: 46.6988,
    timezone: 'UTC+3',
    elevationFt: 2049,
    runwayLengthFt: 13780,
    handlingFeeBase: 2600,
    landingFeeRate: 6.9,
    parkingFeeDaily: 380,
    fuelPricePerGal: 0,
    customsAvailable: true,
    status: 'active',
  },
];

export async function seedInitialUsers(): Promise<void> {
  if (!isMongoConnected()) {
    console.log('ℹ️ [Seed] Skipping initial seed: Database not connected. Admin and fleet records will seed upon valid MongoDB connection.');
    return;
  }

  try {
    // 1. Seed Flight Operations Administrator
    const adminEmail = 'admin@flyayla.com';
    const existingAdmin = await UserService.findByEmailWithPassword(adminEmail);
    if (!existingAdmin) {
      await UserService.createUser({
        firstName: 'Tariq',
        lastName: 'Vance',
        email: adminEmail,
        phone: '+1 (800) 555-0199',
        password: 'AdminPassword123!',
        role: 'admin',
        companyName: 'Fly Ayla Global Flight Operations',
      });
      console.log('👑 [Seed] Initial Flight Operations Admin created: admin@flyayla.com / AdminPassword123!');
    }

    // 2. Seed Initial Fleet and Airports
    await AdminDataService.seedFleetAndAirports(INITIAL_AIRCRAFT, INITIAL_AIRPORTS);
  } catch (error: any) {
    console.error('⚠️ [Seed Error]:', error.message);
  }
}
