import React, { useState } from 'react';
import { 
  Plane, 
  Fuel, 
  Building, 
  Compass, 
  Users, 
  ShieldCheck, 
  Sparkles,
  ArrowRight,
  Info
} from 'lucide-react';
import { FLEET_AIRCRAFT, GLOBAL_AIRPORTS, calculateFlightCost } from '../../data/mockData';

interface PriceBreakdownSectionProps {
  onRequestFlight?: () => void;
}

export const PriceBreakdownSection: React.FC<PriceBreakdownSectionProps> = ({
  onRequestFlight
}) => {
  const [selectedRouteIdx, setSelectedRouteIdx] = useState(0);
  const [marginPct, setMarginPct] = useState(12);

  const sampleRoutes = [
    {
      label: 'London (LTN) → Geneva (GVA)',
      dep: GLOBAL_AIRPORTS[4], // LTN
      arr: GLOBAL_AIRPORTS[6], // GVA
      passengers: 4,
      aircraft: FLEET_AIRCRAFT[0] // Phenom 300E
    },
    {
      label: 'Kuwait (KWI) → Dubai (DXB)',
      dep: GLOBAL_AIRPORTS[0], // OKKK
      arr: GLOBAL_AIRPORTS[5], // OMDB
      passengers: 6,
      aircraft: FLEET_AIRCRAFT[1] // Challenger 350
    },
    {
      label: 'Paris (LBG) → New York (TEB)',
      dep: GLOBAL_AIRPORTS[8], // LFPB
      arr: GLOBAL_AIRPORTS[3], // KTEB
      passengers: 8,
      aircraft: FLEET_AIRCRAFT[2] // Gulfstream G650ER
    }
  ];

  const currentPreset = sampleRoutes[selectedRouteIdx];
  const calculation = calculateFlightCost(
    [{
      departure: currentPreset.dep,
      destination: currentPreset.arr,
      passengers: currentPreset.passengers
    }],
    currentPreset.aircraft,
    marginPct
  );

  return (
    <section className="py-24 sm:py-32 bg-[#0C0C10] text-white border-t border-white/10 relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center max-w-3xl mx-auto mb-16 sm:mb-20">
          <div className="inline-flex items-center gap-2 mb-3">
            <span className="h-2 w-2 rounded-full bg-red-600"></span>
            <span className="text-xs font-semibold uppercase tracking-[0.2em] text-red-500">
              ITEMIZED TRANSPARENCY
            </span>
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white tracking-tight uppercase leading-tight">
            TRANSPARENT PRICE BREAKDOWN.
          </h2>
          <p className="mt-4 text-base sm:text-lg text-zinc-400 leading-relaxed font-normal">
            Every quote generated by Fly Ayla is built upon verifiable direct aviation costs. Explore a live interactive sample breakdown below.
          </p>
        </div>

        {/* Route Preset Bar */}
        <div className="flex flex-wrap items-center justify-center gap-2 mb-10">
          {sampleRoutes.map((rt, idx) => (
            <button
              key={rt.label}
              onClick={() => setSelectedRouteIdx(idx)}
              className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-semibold tracking-wide transition-all cursor-pointer ${
                selectedRouteIdx === idx
                  ? 'bg-red-600 text-white shadow-lg shadow-red-950/80 border border-red-500/50'
                  : 'bg-zinc-900/80 text-zinc-400 hover:text-white border border-white/10 hover:border-white/20'
              }`}
            >
              {rt.label}
            </button>
          ))}
        </div>

        {/* 2-Column Calculator Box */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
          
          {/* Left Column: Cost Itemization Rows */}
          <div className="lg:col-span-7 bg-[#121218] rounded-2xl border border-white/10 p-6 sm:p-8 flex flex-col justify-between shadow-2xl">
            <div>
              <div className="flex items-center justify-between pb-4 border-b border-white/10">
                <div className="flex items-center gap-2">
                  <Plane className="w-5 h-5 text-red-500" />
                  <span className="font-semibold text-white text-base">
                    {currentPreset.aircraft.name}
                  </span>
                  <span className="text-xs text-zinc-400 hidden sm:inline font-normal">
                    ({currentPreset.aircraft.category})
                  </span>
                </div>
                <div className="text-xs text-zinc-400 font-normal">
                  {calculation.legsCalculated[0]?.distanceNm} NM &bull; {calculation.legsCalculated[0]?.estimatedFlightTime}
                </div>
              </div>

              {/* Itemized Rows */}
              <div className="mt-6 space-y-4">
                
                {/* 1. Base Flight & Airframe Cost */}
                <div className="flex items-center justify-between p-3.5 rounded-xl bg-white/5 border border-white/5 hover:border-white/15 transition-all">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-zinc-800 text-zinc-300 flex items-center justify-center">
                      <Plane className="w-4 h-4 text-red-500" />
                    </div>
                    <div>
                      <div className="text-sm font-semibold text-white">Flight Airframe &amp; Engine Base</div>
                      <div className="text-xs text-zinc-400 font-normal">Block hour utilization &amp; airframe amortized reserve</div>
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-zinc-100">
                    ${(calculation.breakdown.fixedCostAllocation || 5200).toLocaleString('en-US', { maximumFractionDigits: 0 })}
                  </div>
                </div>

                {/* 2. Jet-A Fuel Burn */}
                <div className="flex items-center justify-between p-3.5 rounded-xl bg-white/5 border border-white/5 hover:border-white/15 transition-all">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-zinc-800 text-zinc-300 flex items-center justify-center">
                      <Fuel className="w-4 h-4 text-red-500" />
                    </div>
                    <div>
                      <div className="text-sm font-semibold text-white">Jet-A Fuel Burn &amp; Uplift</div>
                      <div className="text-xs text-zinc-400 font-normal">Direct contract rate via official JetFuelX feed</div>
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-zinc-100">
                    {calculation.breakdown.fuelCost !== null && calculation.breakdown.fuelCost > 0 ? (
                      `$${calculation.breakdown.fuelCost.toLocaleString('en-US', { maximumFractionDigits: 0 })}`
                    ) : (
                      <span className="text-amber-400/90 text-xs italic font-normal">
                        JetFuelX API key required
                      </span>
                    )}
                  </div>
                </div>

                {/* 3. Airport Handling & FBO Ramp Fees */}
                <div className="flex items-center justify-between p-3.5 rounded-xl bg-white/5 border border-white/5 hover:border-white/15 transition-all">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-zinc-800 text-zinc-300 flex items-center justify-center">
                      <Building className="w-4 h-4 text-red-500" />
                    </div>
                    <div>
                      <div className="text-sm font-semibold text-white">Airport Handling &amp; FBO Ramp Fees</div>
                      <div className="text-xs text-zinc-400 font-normal">Landing tariffs, VIP lounge, ramp transit, &amp; parking</div>
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-zinc-100">
                    ${calculation.breakdown.handlingCost.toLocaleString('en-US', { maximumFractionDigits: 0 })}
                  </div>
                </div>

                {/* 4. Navigation & FIR Airspace Fees */}
                <div className="flex items-center justify-between p-3.5 rounded-xl bg-white/5 border border-white/5 hover:border-white/15 transition-all">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-zinc-800 text-zinc-300 flex items-center justify-center">
                      <Compass className="w-4 h-4 text-red-500" />
                    </div>
                    <div>
                      <div className="text-sm font-semibold text-white">Navigation &amp; FIR Overflight Fees</div>
                      <div className="text-xs text-zinc-400 font-normal">Eurocontrol &amp; civil airspace en-route vector charges</div>
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-zinc-100">
                    ${calculation.breakdown.navFees.toLocaleString('en-US', { maximumFractionDigits: 0 })}
                  </div>
                </div>

                {/* 5. Crew Logistics & Catering */}
                <div className="flex items-center justify-between p-3.5 rounded-xl bg-white/5 border border-white/5 hover:border-white/15 transition-all">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-zinc-800 text-zinc-300 flex items-center justify-center">
                      <Users className="w-4 h-4 text-red-500" />
                    </div>
                    <div>
                      <div className="text-sm font-semibold text-white">Crew Logistics &amp; Inflight Service</div>
                      <div className="text-xs text-zinc-400 font-normal">Captain &amp; First Officer per diems, handling, catering</div>
                    </div>
                  </div>
                  <div className="text-sm font-semibold text-zinc-100">
                    ${calculation.breakdown.fixedCostAllocation.toLocaleString('en-US', { maximumFractionDigits: 0 })}
                  </div>
                </div>

              </div>
            </div>

            <div className="mt-6 pt-4 border-t border-white/10 flex items-center gap-2 text-xs text-zinc-400 font-normal">
              <Info className="w-4 h-4 text-red-500 shrink-0" />
              <span>Zero hidden broker markups. All numbers computed directly from verified aviation tariffs.</span>
            </div>
          </div>

          {/* Right Column: Total Price Card & Dispatch */}
          <div className="lg:col-span-5 bg-gradient-to-b from-[#181822] to-[#0F0F16] rounded-2xl border border-red-500/30 p-6 sm:p-8 flex flex-col justify-between shadow-2xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-48 h-48 bg-red-600/10 blur-3xl pointer-events-none rounded-full" />

            <div>
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-red-950/60 border border-red-500/30 text-xs font-semibold text-red-400 uppercase tracking-wide mb-6">
                <Sparkles className="w-3.5 h-3.5" /> Direct Quoted Price
              </div>

              <div className="space-y-2">
                <div className="text-xs font-semibold text-zinc-400 uppercase tracking-wider">
                  TOTAL ESTIMATED TRIP PRICE
                </div>
                <div className="text-4xl sm:text-5xl font-bold text-red-500 tracking-tight">
                  ${calculation.breakdown.quotedTotal.toLocaleString('en-US', { maximumFractionDigits: 0 })}
                </div>
                <p className="text-xs text-zinc-400 leading-relaxed pt-2 font-normal">
                  Includes aircraft positioning, passenger taxes, VIP private terminal escort, and Michelin-standard bespoke catering.
                </p>
              </div>

              {/* Summary Checklist */}
              <div className="mt-8 space-y-3 pt-6 border-t border-white/10">
                <div className="flex items-center justify-between text-xs text-zinc-300">
                  <span className="font-normal">Aircraft Category:</span>
                  <span className="font-semibold text-white">{currentPreset.aircraft.category}</span>
                </div>
                <div className="flex items-center justify-between text-xs text-zinc-300">
                  <span className="font-normal">Guaranteed Departure Time:</span>
                  <span className="font-semibold text-white">Within 3 Hours</span>
                </div>
                <div className="flex items-center justify-between text-xs text-zinc-300">
                  <span className="font-normal">Private FBO Handling:</span>
                  <span className="font-semibold text-white">Included</span>
                </div>
                <div className="flex items-center justify-between text-xs text-zinc-300">
                  <span className="font-normal">De-Icing &amp; Weather Contingency:</span>
                  <span className="font-semibold text-white">Clearance Verified</span>
                </div>
              </div>
            </div>

            {/* CTA button */}
            <div className="mt-8 pt-4">
              <button
                onClick={onRequestFlight}
                className="w-full py-3.5 px-6 rounded-xl bg-gradient-to-r from-red-600 to-rose-700 hover:from-red-500 hover:to-rose-600 text-white text-sm font-semibold tracking-wide uppercase flex items-center justify-center gap-2 shadow-xl shadow-red-950/80 transition-all cursor-pointer leading-tight"
              >
                <span>Request Itinerary Quote</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>

          </div>

        </div>

      </div>
    </section>
  );
};
